version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=${MONGO_URL}
      - DB_NAME=${DB_NAME}
      - IMAGE_API_KEY=${IMAGE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27023:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
