name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 5432:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: docker-compose build

      - name: Run tests
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
          IMAGE_API_KEY: ${{ secrets.IMAGE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
        run: docker-compose run --rm app npm test

      - name: Push Docker image
        run: |
          docker tag carspecsfinderai-api_app:latest ${{ secrets.DOCKER_USERNAME }}/carspecsfinderai-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/carspecsfinderai-api:latest
