name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27018:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.0"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
          IMAGE_API_KEY: ${{ secrets.IMAGE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          DB_COLLECTION: ${{ secrets.DB_COLLECTION }}
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker-compose build
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
          IMAGE_API_KEY: ${{ secrets.IMAGE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          DB_COLLECTION: ${{ secrets.DB_COLLECTION }}

      - name: Run tests in Docker
        run: docker-compose run --rm app npm test
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
          IMAGE_API_KEY: ${{ secrets.IMAGE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          DB_COLLECTION: ${{ secrets.DB_COLLECTION }}

      - name: Tag and push Docker image
        run: |
          docker tag carspecsfinderai-api_app:latest ${{ secrets.DOCKER_USERNAME }}/carspecsfinderai-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/carspecsfinderai-api:latest

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Azure App Service with new image
        run: |
          az webapp config container set \
            --resource-group CarSpecsFinder \
            --name api-dockerhub \
            --container-image-name ${{ secrets.DOCKER_USERNAME }}/carspecsfinderai-api:latest
